version: "3.9"

services:
     restaurant-frontend:
          container_name: restaurant-fe
          build:
               context: .
               dockerfile: Dockerfile
          volumes:
               - ".:/app"
               - "/app/node_modules"
          ports:
               - "2555:80"
          environment:
               - NODE_ENV=development